[versions]
kotlinVersion="1.9.22"
lwJavaVersion="0.2.18-SNAPSHOT"

[plugins]
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version = "12.1.0" }
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlinVersion" }
dokka = { id = "org.jetbrains.dokka", version = "1.9.20" }
superPublish = { id = "com.vanniktech.maven.publish", version = "0.29.0" }
buildConfig = { id = "com.github.gmazzo.buildconfig", version = "5.3.5" }
release = { id = "net.researchgate.release", version = "3.0.2"}

[libraries]
okhttp = { group = "com.squareup.okhttp3", name="okhttp", version="4.12.0"}
gson = { group = "com.google.code.gson", name="gson", version="2.10.1" }
annotations = { group = "org.jetbrains", name="annotations", version="24.0.0" }
junit = { group = "junit", name="junit", version="4.13" }
kotlinreflect = { group = "org.jetbrains.kotlin", name="kotlin-reflect", version.ref = "kotlinVersion" }
ktestjunit = { group = "org.jetbrains.kotlin", name = "kotlin-test-junit5", version.ref = "kotlinVersion" }
lwjavacore = { group = "io.lionweb.lionweb-java", name = "lionweb-java-2023.1-core", version.ref = "lwJavaVersion"}
lwjavaextensions = { group = "io.lionweb.lionweb-java", name = "lionweb-java-2023.1-extensions", version.ref = "lwJavaVersion"}

emfcommon = { group = "org.eclipse.emf", name="org.eclipse.emf.common", version="2.28.0" }
ecore = { group = "org.eclipse.emf", name="org.eclipse.emf.ecore", version="2.33.0" }
ecore-xmi = { group = "org.eclipse.emf", name="org.eclipse.emf.ecore.xmi", version="2.18.0" }
emfjson = { group = "org.eclipse.emfcloud", name="emfjson-jackson", version="2.2.0" }
