name: Functional Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '11' ]
    name: Java ${{ matrix.Java }} Check

    steps:
      - uses: actions/checkout@v1
      - name: Setup java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java }}
      - name: Functional Tests
        run: ./gradlew functionalTest --stacktrace
